### ISSUE TITLE
Nightly builds failing due to a broken link

### ISSUE THREAD

**Issue by erogluorhan** [ProjectPythiaCookbooks/HRRR-AWS-cookbook#33]
**What happened**:

Dear authors (cc'ing @ktyle and @brian-rose as you have the two largest contributions), the nightly builds of this cookbook have been failing for about the last month due to a broken link (https://pangeo.io/data.html). 

Could you please have a look at it?

**Minimal Complete Verifiable Example**:

[Latest nightly build](https://github.com/ProjectPythia/HRRR-AWS-cookbook/actions/runs/11376534961/job/31649173416) as of the creation of this issue.

**Anything else we need to know?**:

If you think it is due to Pythia infrastructure or something else other than the cookbook itself, please let us know.

**Comment by brian-rose** [comment]
Hi @ktyle, the link failure is in the [What is Zarr](https://projectpythia.org/HRRR-AWS-cookbook/notebooks/example-workflows/2mT.html#what-is-zarr) section of your notebook. There's a quote from a Pangeo web page that no longer exists. I'm not sure whether we just want to remove the quote and the link, or replace it with something more recent (e.g. from the [Zarr documentation](https://zarr.readthedocs.io/en/stable/index.html)) that briefly describes what Zarr is and what are its advantages for data in the cloud.

What do you think?

**Comment by ktyle** [comment]
@brian-rose and @erogluorhan thanks for letting me know; the PR should address it. Although the quote no longer seems to exist on the newly-refreshed Pangeo site, I still think it's the best short/clear description of the advantages of Zarr for the Pangeo ecosystem (at least I haven't found anything I like more at this time).

**Comment by erogluorhan** [comment]
Sounds good; thanks for the fix!
